[package]
name = "dnbradio-bot"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "dnbradio-bot"
path = "src/main.rs"

[profile.release]
strip = true

[dependencies]
chrono = "0.4.31"
dotenvy = "0.15.7"
tokio = { version = "1.35.1", features = ["rt", "rt-multi-thread", "macros"] }
anyhow = "1.0.79"
serenity = "0.12.0"
irc = { version = "0.15.0", default-features = false, features = ["tls-rust"] }
async-trait = "0.1.75"
futures = "0.3.30"
reqwest = { version = "0.11.23", default-features = false, features = ["json", "rustls-tls"] }
serde = "1.0.195"
serde_json = "1.0.108"
env_logger = "0.10.1"
minimp3 = { version = "0.5.1", features = ["async_tokio"] }
log = "0.4.20"
chfft = "0.3.4"
dasp = { version = "0.11.0", features = ["signal", "interpolate", "interpolate-sinc", "ring_buffer"] }
rand = "0.8.5"
uuid = { version = "1.6.1", features = ["v4"] }
byteorder = "1.5.0"
crc32fast = "1.3.2"
base64 = "0.21.5"
dyn-fmt = "0.4.0"
